# Generated by Django 4.2.7 on 2025-09-26 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('home_terminal_address', models.TextField()),
                ('carrier_name', models.CharField(max_length=200)),
                ('carrier_address', models.TextField()),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('hos_rule_type', models.CharField(choices=[('70_8', '70 hours/8 days'), ('60_7', '60 hours/7 days')], default='70_8', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_address', models.TextField()),
                ('origin_coordinates', models.CharField(max_length=50)),
                ('destination_address', models.TextField()),
                ('destination_coordinates', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='eld_app.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('driving', 'Driving'), ('fuel_stop', 'Fuel Stop'), ('rest_break', 'Rest Break'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('sleeper_berth', 'Sleeper Berth')], max_length=20)),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('start_coordinates', models.CharField(max_length=50)),
                ('end_coordinates', models.CharField(max_length=50)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planned_start_time', models.DateTimeField()),
                ('planned_end_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='eld_app.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('driving_limit', '11-Hour Driving Limit'), ('duty_limit', '14-Hour Duty Limit'), ('weekly_limit', '70/60-Hour Weekly Limit'), ('rest_break', '30-Minute Rest Break'), ('off_duty', '10-Hour Off Duty')], max_length=20)),
                ('violation_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='eld_app.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='eld_app.trip')),
            ],
            options={
                'ordering': ['-violation_time'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=50)),
                ('planned_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='eld_app.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_statuses', to='eld_app.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_statuses', to='eld_app.trip')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('total_miles_driven', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vehicle_numbers', models.CharField(max_length=200)),
                ('origin_location', models.CharField(blank=True, max_length=200)),
                ('destination_location', models.CharField(blank=True, max_length=200)),
                ('shipping_documents', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('on_duty_not_driving_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_hours_last_7_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_hours_last_5_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('hours_available_tomorrow', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='eld_app.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='eld_app.trip')),
            ],
            options={
                'ordering': ['-log_date'],
                'unique_together': {('driver', 'log_date')},
            },
        ),
    ]
