# Generated by Django 4.2.7 on 2025-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_state',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
